version: '3.1'

services:
  db:
    image: mysql:5.6
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_lar_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80

volumes:
  dbbase:
